ALTER TABLE purchase_orders
    ADD COLUMN IF NOT EXISTS approval_status VARCHAR(32) NOT NULL DEFAULT 'NOT_SUBMITTED',
    ADD COLUMN IF NOT EXISTS order_date DATE DEFAULT CURRENT_DATE,
    ADD COLUMN IF NOT EXISTS expected_delivery_date DATE,
    ADD COLUMN IF NOT EXISTS currency VARCHAR(3) NOT NULL DEFAULT 'TRY',
    ADD COLUMN IF NOT EXISTS created_by VARCHAR(100),
    ADD COLUMN IF NOT EXISTS description TEXT;

ALTER TABLE purchase_order_items
    ADD COLUMN IF NOT EXISTS vat_rate DECIMAL(5, 2) NOT NULL DEFAULT 20;
